### ISSUE TITLE
Upgrade cargo-generate-rpm?

### ISSUE THREAD

**Issue by ximon18** [NLnetLabs/ploutos#61]
We're currently locked to v0.8.0. This actually traces back to Routinator commit [https://github.com/NLnetLabs/routinator/commit/b8c1bcb34d256e28d43950cf38de7361d4f54880] prior to their being a single unified Ploutos workflow in use at NLnet Labs. The commit message for that commit is revealing:

> Upgrade cargo-generate-rpm and remove no longer needed workaround.

So, we were locked to a specific version of cargo-generate-rpm because of a problem, but now we just lock to a version to avoid unexpected headaches caused by automatic use of a newer version, not because there's a known problem with a newer version.

Since v0.8.0 there have been the following cargo-generate-rpm releases with the following notable changes in v0.10.0:

- Support for rpm file which does not have a dependency on /bin/sh by @cat-in-136 in https://github.com/cat-in-136/cargo-generate-rpm/pull/52
- Add optional fields url and vendor by @RocketJas in https://github.com/cat-in-136/cargo-generate-rpm/pull/54 and @cat-in-136 in https://github.com/cat-in-136/cargo-generate-rpm/pull/55
- fix bug (https://github.com/cat-in-136/cargo-generate-rpm/issues/37) of glob in assets in combination with a workspace project and support for https://github.com/cat-in-136/cargo-generate-rpm/issues/50 directory target of non-glob assets by @cat-in-136 in https://github.com/cat-in-136/cargo-generate-rpm/pull/53
- Upgrading of dependent libraries
  - switch to maintained fork of rpm-rs, rpm-rs/rpm by @drahnr in https://github.com/cat-in-136/cargo-generate-rpm/pull/51
  - upgrade elf crate to version 0.7.x. by @cat-in-136 in https://github.com/cat-in-136/cargo-generate-rpm/pull/56

Changes in earlier versions that affected the logic only related to Cargo Workspaces and those have never been tried with Ploutos and may not work anyway for reasons unrelated to cargo-generate-rpm.

The support for additional url and vendor fields might be something we want to enable users of Ploutos to take advantage of.

We should also clearly document which version of cargo-generate-rpm we support otherwise users might try using cargo-generate-rpm features which are only in a version newer than the one we use!

**Comment by drahnr** [comment]
@ximon18 the changes required to move to `rpm/rpm-rs` are outline in `cargo-generate-rpm` - it's only a few methods that got reparented. If you need help, mention me in your PR

**Comment by ximon18** [comment]
The [Ploutos v7.0.0 release](https://github.com/NLnetLabs/ploutos/releases/tag/v7.0.0) upgraded cargo-generate-rpm to latest to resolve issues with Cargo workspaces.
